### ISSUE TITLE
Water Volume and Temperature are next to each other compared to the above way

### ISSUE THREAD

**Issue by Mimoja** [barneyhawes1/decent-metric#3]
![grafik](https://user-images.githubusercontent.com/10907336/111613413-c440c280-87de-11eb-8637-3ab1bb19fefe.png)

Everywhere else in the skin the up / down buttons are stacked on top of each other. Here the UI breaks, suggesting the Unit can be changed, instead of the value

**Comment by barneyhawes** [comment]
This was how they used to be look in an earlier iteration. This page was not updated with the new look.

This page has now been removed, so there are no options to configure steam or water in this skin(!).
