### ISSUE TITLE
Missing $ in ::color_yield

### ISSUE THREAD

**Issue by ebengoechea** [barneyhawes1/decent-metric#7]
Hi @barneyhawes, while testing the metric skin with the forthcoming 'de1_dui' package I found this tiny bug: on line 62 of pages/espresso_done.tcl you have "-color ::color_yield" instead of "-color **$**::color_yield" (i.e. a missing "$"), which prevents the correct loading of your skin.

**Comment by barneyhawes** [comment]
Thanks, well spotted. This is now fixed.
