### ISSUE TITLE
Duplicated loading of de1_skin_settings.tcl

### ISSUE THREAD

**Issue by ebengoechea** [barneyhawes1/decent-metric#8]
@barneyhawes I'm hitting a bug with the metric skin after a change I've made in DUI. DUI now checks that all GUI pages declared with 'add_de1_page' or 'dui page add' are unique, to detect potential errors. When used with metric, it raises an error because page "settings_1" is being declared twice. I've looked at your code and this is because you are explicitly sourcing skins/default/de1_skin_settings.tcl, but this is not needed because the default skin is already always loaded, so that file is being sourced twice.

I've checked that commenting line 38 in skins/metric/skin.tcl solves the problem and apparently has no side effect (the settings still show correctly). Could you please have a look and, if you confirm it has no ill effect, remove that line?

**Comment by barneyhawes** [comment]
This has now been removed.
